### PR TITLE
Updated material-theme with more usable and subtle colors for ediff 

### PR DESCRIPTION
**Pull request by howdypierce**
Previous colors were garish and not legible when in ediff mode. The unhighlighted regions (what ediff calls the "ediff-odd" and "ediff-even" faces) were particularly illegible. Addressed this with some more subtle colors. Attached screenshots show "before" and "after" on a 3-way merge.

material-ediff-before
material-ediff-now

### CODE REVIEW

**Comment by cpaulik** [comment]
Thanks. That looks much better.

**Comment by cpaulik** [comment]
I had to revert https://github.com/cpaulik/emacs-material-theme/commit/11e525cba2d9cef6ba3ffba6190fb274d0aa56b9

Didn't notice before that that was also included.

**Comment by howdypierce** [comment]
Thanks. Sorry about the other changes -- I did not expect that those were of interest for general consumption. I thought when I made a pull-request that it was specific to a particular commit in time, but evidently not.

**Comment by cpaulik** [comment]
No problem at all. I should have checked closer before merging.

MR are related to a branch. It's handy for adding changes during review for example.

**Pull request merged**
